# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "alexsmobs:snow_leopard",
    "minecolonies:campamazonchief",
    "aquaculture:pink_salmon",
    "infectious:zombie_batman",
    "dayzombierebooted:spawner",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "aquaculture:muskellunge",
    "minecraft:llama",
    "alexsmobs:skreecher",
    "minecraft:tadpole",
    "infectious:nuke_explosion",
    "infectious:bike",
    "minecolonies:pirate",
    "alexsmobs:hammerhead_shark",
    "infectious:maggot_zombie",
    "infectious:deep_sea_diver_zombie",
    "naturalist:bear",
    "alexsmobs:grizzly_bear",
    "infectious:construction_worker_zombie",
    "naturalist:vulture",
    "alexsmobs:murmur_head",
    "naturalist:zebra",
    "minecolonies:archerbarbarian",
    "infectious:zombified_bird_flying",
    "infectious:balloon_zombie",
    "infectious:zombified_bear",
    "infectious:iron_door_zombie",
    "minecraft:mooshroom",
    "infectious:zombie_spiter",
    "infectious:zombie_clown",
    "minecraft:axolotl",
    "ad_astra:martian_raptor",
    "burnt:fire_devil",
    "infectious:psycho_zombie",
    "alexsmobs:gorilla",
    "alexsmobs:cosmic_cod",
    "aquaculture:pacific_halibut",
    "naturalist:cardinal",
    "alexsmobs:kangaroo",
    "infectious:zombie_screamer",
    "bloomingnature:termite",
    "infectious:zombie_miner",
    "alexsmobs:hummingbird",
    "ad_astra:sulfur_creeper",
    "infectious:zombified_chicken",
    "alexsmobs:crow",
    "minecolonies:campmummy",
    "alexsmobs:guster",
    "infectious:zombie_doctor",
    "infectious:franklin_zombie",
    "bloomingnature:wandering_gardener",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "alexsmobs:emu",
    "ad_astra:glacian_ram",
    "superbwarfare:senpai",
    "aquaculture:tambaqui",
    "infectious:zombie_bomber",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "canned_goods:canned_golem",
    "infectious:zombie_on_stelts",
    "aquaculture:brown_shrooma",
    "minecolonies:drownedarcherpirate",
    "minecraft:zombified_piglin",
    "naturalist:rattlesnake",
    "minecraft:sheep",
    "infectious:screamer",
    "naturalist:robin",
    "naturalist:tortoise",
    "alexsmobs:bone_serpent_part",
    "alexsmobs:raccoon",
    "minecraft:ravager",
    "infectious:spore_zombie",
    "infectious:zombified_rex",
    "alexsmobs:bone_serpent",
    "superbwarfare:steel_coil",
    "minecolonies:amazon",
    "infectious:big_zombie",
    "bakery:wandering_baker",
    "alexsmobs:mudskipper",
    "alexsmobs:crimson_mosquito",
    "infectious:mummy",
    "infectious:doom_zombie",
    "infectious:infectious_zombie",
    "infectious:door_zombie",
    "alexsmobs:jerboa",
    "infectious:lootdrop",
    "minecolonies:mummy",
    "alexsmobs:comb_jelly",
    "naturalist:hippo",
    "naturalist:snake",
    "railways:conductor",
    "ad_astra:zombified_mogler",
    "infectious:security_zombie",
    "naturalist:catfish",
    "alexsmobs:enderiophage",
    "alexsmobs:sunbird",
    "minecraft:cat",
    "infectious:zombie_hitler",
    "naturalist:lizard",
    "infectious:bees",
    "minecraft:tropical_fish",
    "naturalist:snail",
    "naturalist:finch",
    "minecraft:zombie_villager",
    "alexsmobs:froststalker",
    "minecraft:giant",
    "alexsmobs:lobster",
    "minecolonies:archerpirate",
    "alexsmobs:seagull",
    "aquaculture:atlantic_herring",
    "infectious:pumpkin_zombie",
    "ad_astra:corrupted_lunarian",
    "aquaculture:bluegill",
    "minecraft:husk",
    "mca:female_zombie_villager",
    "naturalist:firefly",
    "minecolonies:mercenary",
    "minecraft:donkey",
    "minecolonies:shieldmaiden",
    "minecraft:piglin_brute",
    "infectious:zombie_runner",
    "superbwarfare:target",
    "naturalist:giraffe",
    "minecolonies:drownedchiefpirate",
    "burnt:falling_slab",
    "infectious:hazmat_zombie",
    "aquaculture:jellyfish",
    "alexsmobs:frilled_shark",
    "alexsmobs:bald_eagle",
    "alexsmobs:blobfish",
    "aquaculture:blackfish",
    "alexsmobs:void_worm",
    "burnt:volcano",
    "minecraft:parrot",
    "alexsmobs:centipede_head",
    "aquaculture:carp",
    "alexsmobs:banana_slug",
    "minecolonies:camppirate",
    "infectious:barrel_zombie",
    "infectious:frozen_zombie",
    "infectious:fire_fighter_zombie",
    "naturalist:alligator",
    "aquaculture:boulti",
    "infectious:zombie_diver",
    "alexsmobs:bunfungus",
    "infectious:zombie_horseman",
    "infectious:golden_zombie",
    "minecraft:mule",
    "naturalist:boar",
    "minecraft:vindicator",
    "infectious:zombie_cook",
    "infectious:muddy_zombie",
    "alexsmobs:flying_fish",
    "minecolonies:chiefbarbarian",
    "aquaculture:synodontis",
    "infectious:zombified_boar",
    "infectious:ancient_zombie_boss",
    "infectious:zombie_soldier",
    "burnt:tomb_spawner",
    "infectious:zombie_prisoner",
    "infectious:burned_zombie",
    "aquaculture:catfish",
    "burnt:burnt_forest_spawner",
    "radiotowers:airdropentity",
    "alexsmobs:terrapin",
    "burnt:grave_spawner",
    "infectious:zombie_astronaut",
    "infectious:fat_zombie",
    "minecolonies:campamazonspearman",
    "mca:grim_reaper",
    "infectious:pylon_zombie",
    "minecraft:pig",
    "alexsmobs:alligator_snapping_turtle",
    "aquaculture:atlantic_halibut",
    "ad_astra:pygro",
    "minecraft:cod",
    "infectious:zombie_head",
    "aquaculture:red_grouper",
    "infectious:zombie_scientist",
    "infectious:balloon_zombie_no_balloon",
    "alexsmobs:platypus",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "aquaculture:rainbow_trout",
    "naturalist:duck",
    "alexsmobs:soul_vulture",
    "alexsmobs:blue_jay",
    "minecraft:salmon",
    "dyairdrop:airdrop",
    "alexsmobs:anteater",
    "alexsmobs:rain_frog",
    "burnt:wisp",
    "infectious:zombie_bait",
    "minecraft:rabbit",
    "minecraft:pillager",
    "infectious:zombie_breeder",
    "minecraft:zoglin",
    "aquaculture:piranha",
    "naturalist:butterfly",
    "alexsmobs:leafcutter_ant",
    "butchery:turtleshellboat",
    "infectious:zombie_dancer",
    "minecolonies:cavalry_horse",
    "infectious:old_zombie",
    "naturalist:lion",
    "aquaculture:arrau_turtle",
    "naturalist:canary",
    "alexsmobs:gazelle",
    "minecraft:sniffer",
    "infectious:acid_zombie",
    "infectious:claw_zombie",
    "naturalist:coral_snake",
    "minecolonies:pharao",
    "ad_astra:mogler",
    "alexsmobs:seal",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "meadow:wooly_sheep",
    "infectious:zombie_painter",
    "aquaculture:bayad",
    "alexsmobs:maned_wolf",
    "infectious:glitched_zombie",
    "minecraft:dolphin",
    "alexsmobs:gelada_monkey",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "infectious:zombified_spider",
    "burnt:tar_splash",
    "minecraft:bee",
    "aquaculture:perch",
    "alexsmobs:devils_hole_pupfish",
    "minecraft:illusioner",
    "radiotowers:planeentity",
    "minecolonies:barbarian",
    "alexsmobs:bison",
    "infectious:swat_zombie",
    "simpleenemymod:pmcunit",
    "minecraft:drowned",
    "minecolonies:drownedpirate",
    "minecolonies:chiefpirate",
    "aquaculture:arapaima",
    "naturalist:moose",
    "alexsmobs:tusklin",
    "infectious:pool_tube_zombie",
    "infectious:zombie_agent",
    "naturalist:elephant",
    "ad_astra:zombified_pygro",
    "alexsmobs:underminer",
    "minecraft:wandering_trader",
    "hordes:drowned_player",
    "dyairdrop:plane",
    "aquaculture:atlantic_cod",
    "minecraft:pufferfish",
    "aquaculture:starshell_turtle",
    "minecraft:fox",
    "minecolonies:campdrownedpirate",
    "immersiveengineering:bulwark",
    "alexsmobs:warped_toad",
    "minecolonies:campshieldmaiden",
    "minecolonies:campamazon",
    "immersiveengineering:fusilier",
    "alexsmobs:cockroach",
    "infectious:tower_zombie",
    "infectious:zombie_warrior",
    "infectious:zombie_horde",
    "naturalist:rhino",
    "alexsmobs:capuchin_monkey",
    "hordes:husk_player",
    "minecraft:polar_bear",
    "aquaculture:brown_trout",
    "minecraft:turtle",
    "infectious:crawling_zombie",
    "infectious:zombie_fisherman",
    "infectious:zombie_miner_spawn",
    "alexsmobs:rattlesnake",
    "minecolonies:norsemenarcher",
    "minecolonies:citizen",
    "infectious:headless_zombie",
    "alexsmobs:potoo",
    "minecolonies:campnorsemenarcher",
    "alexsmobs:fly",
    "dyairdrop:weaponairdrop",
    "minecolonies:archermummy",
    "infectious:zombie_horseman_no_horse",
    "minecolonies:campnorsemenchief",
    "alexsmobs:straddler",
    "alexsmobs:sea_bear",
    "minecolonies:campdrownedchiefpirate",
    "ad_astra:pygro_brute",
    "burnt:molotov_tar",
    "alexsmobs:sugar_glider",
    "infectious:mc_donalds_worker_zombie",
    "infectious:fungal_zombie",
    "minecolonies:camparchermummy",
    "naturalist:bass",
    "minecolonies:amazonspearman",
    "infectious:zombified_wolf",
    "alexsmobs:orca",
    "naturalist:dragonfly",
    "infectious:firework_zombie",
    "minecraft:bat",
    "naturalist:sparrow",
    "alexsmobs:cosmaw",
    "infectious:mecha_zombie",
    "naturalist:lizard_tail",
    "infectious:baseball_bat_zombie",
    "naturalist:caterpillar",
    "alexsmobs:skunk",
    "minecolonies:campdrownedarcherpirate",
    "alexsmobs:tasmanian_devil",
    "infectious:tower_zombie_1",
    "alexsmobs:stradpole",
    "infectious:chained_zombie",
    "ad_astra:lunarian_wandering_trader",
    "infectious:bucket_zombie",
    "minecolonies:norsemenchief",
    "minecolonies:campchiefbarbarian",
    "minecraft:panda",
    "infectious:muscular_zombie",
    "infectious:tower_zombie_4",
    "infectious:tower_zombie_3",
    "infectious:tower_zombie_2",
    "dyairdrop:medicalairdrop",
    "dyairdrop:transportplane",
    "burnt:soul_spawner",
    "alexsmobs:moose",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "burnt:smoke",
    "infectious:atomic_mushroom",
    "infectious:robotic_zombie",
    "alexsmobs:warped_mosco",
    "immersiveengineering:commando",
    "meadow:wooly_cow",
    "hordes:zombie_player",
    "infectious:mutation_trigger",
    "minecolonies:amazonchief",
    "alexsmobs:komodo_dragon",
    "infectious:mutant_zombie",
    "infectious:blind_zombie",
    "infectious:beehive_zombie",
    "minecolonies:camppharao",
    "simpleenemymod:ruunit",
    "alexsmobs:crocodile",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "infectious:giant_zombie",
    "aquaculture:tuna",
    "naturalist:deer",
    "alexsmobs:mimicube",
    "dyairdrop:smallairdrop",
    "infectious:zombie_lumberjack",
    "infectious:angry_zombie",
    "vinery:mule",
    "ad_astra:lunarian",
    "minecraft:frog",
    "infectious:enchanted_zombie",
    "minecolonies:camparcherbarbarian",
    "yungscavebiomes:sand_snapper",
    "infectious:armless_zombie",
    "alexsmobs:mimic_octopus",
    "infectious:nuke",
    "alexsmobs:void_worm_part",
    "minecolonies:campbarbarian",
    "vinery:wandering_winemaker",
    "minecraft:evoker",
    "alexsmobs:tarantula_hawk",
    "aquaculture:smallmouth_bass",
    "alexsmobs:cachalot_whale",
    "infectious:bodyless_zombie",
    "infectious:turret",
    "aquaculture:minnow",
    "infectious:sleepy_zombie",
    "infectious:football_player_zombie",
    "infectious:brain_zombie",
    "alexsmobs:anaconda",
    "infectious:withered_zombie",
    "infectious:zombie_boxer",
    "aquaculture:red_shrooma",
    "infectious:beekeeper_zombie",
    "minecraft:goat",
    "mca:male_zombie_villager",
    "aquaculture:gar",
    "alexsmobs:mantis_shrimp",
    "meadow:water_buffalo",
    "minecolonies:visitor",
    "infectious:zombie_archer",
    "infectious:burning_zombie",
    "infectious:zombie_police",
    "alexsmobs:toucan",
    "naturalist:bluejay",
    "infectious:zombified_bird",
    "yungscavebiomes:ice_cube",
    "ad_astra:star_crawler",
    "alexsmobs:murmur",
    "infectious:zombie_farmer",
    "infectious:zombie_girl",
    "aquaculture:box_turtle",
    "infectious:bouncer_zombie",
    "alexsmobs:mungus",
    "alexsmobs:caiman",
    "alexsmobs:spectre",
    "tacz_bandits:bandit",
    "alexsmobs:catfish",
    "aquaculture:pollock",
    "minecraft:piglin",
    "alexsmobs:skelewag",
    "alexsmobs:elephant",
    "aquaculture:capitaine",
    "infectious:radioactive_zombie",
    "infectious:zombie",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "minecolonies:camparcherpirate",
    "infectious:disco_zombie",
    "superbwarfare:dps_generator",
    "infectious:ancient_zombie",
    "minecolonies:campchiefpirate",
    "infectious:zombie_climber",
    "burnt:geyser",
    "minecraft:ocelot",
    "minecraft:wolf"
]
