#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 02 13:37:02 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=ComplementaryUnbound_r5.8.1.zip
enableShaders=true
